In [1]:
# l2 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a) # [1 2 3]
l2 = norm(a)
print(l2) # 3.7416573867739413

[1 2 3]
3.7416573867739413


# Vector Norms

Source: [Gentle Introduction to Vector Norms in Machine Learning](https://machinelearningmastery.com/vector-norms-machine-learning/)

- The $$L_1$$ norm that is calculated as the sum of the absolute values of the vector.
- The L norm that is calculated as the square root of the sum of the squared vector values.
- The max norm that is calculated as the maximum vector values.

## $L_1$ Norm


- The $$L_1$$ norm of a vector can be calculated in `NumPy` using the `norm()` function with a parameter to specify the norm order, in this case 1.

```python
# l1 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a) # [1 2 3]
l1 = norm(a, 1)
print(l1) # 6
```

## $$L_2$$ Norm

- The $$L_2$$ norm of a vector can be calculated in `NumPy` using the `norm()` function with default parameters.

```python
# l2 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a) # [1 2 3]
l2 = norm(a)
print(l2) # 3.7416573867739413
```

## Max Norm

The max norm of a vector can be calculated in `NumPy` using the `norm()` function with the order parameter set to inf.
# max norm of a vector
from numpy import inf
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
maxnorm = norm(a, inf)
print(maxnorm)
1
2
3
4
5
6
7

8
# max norm of a vector
from numpy import inf
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
maxnorm = norm(a, inf)
print(maxnorm)
First, a 1×3 vector is defined, then the max norm of the vector is calculated.
Running the example first prints the defined vector and then the vector’s max norm.
[1 2 3]
3.0
1
2
3
[1 2 3]

3.0
Max norm is also used as a regularization in machine learning, such as on neural network weights, called max norm regularization.
Extensions
This section lists some ideas for extending the tutorial that you may wish to explore.
Create 5 examples using each operation using your own data.
Implement each matrix operation manually for matrices defined as lists of lists.
Search machine learning papers and find 1 example of each operation being used.
If you explore any of these extensions, I’d love to know.
Further Reading
This section provides more resources on the topic if you are looking to go deeper.
Books
Introduction to Linear Algebra, 2016.
Chapter 2, Linear Algebra, Deep Learning, 2016.
API
numpy.linalg.norm() API
Articles
Norm (mathematics) on Wikipedia
Summary

$$\begin{Vmatrix}
\boldsymbol{v}
\end{Vmatrix}_1$$

In this tutorial, you discovered the different ways to calculate vector lengths or magnitudes, called the vector norm.
Specifically, you learned:
The L1 norm that is calculated as the sum of the absolute values of the vector.
The L2 norm that is calculated as the square root of the sum of the squared vector values.
The max norm that is calculated as the maximum vector values.
Do you have any questions?
Ask your questions in the comments below and I will do my best to answer.

|  | L1 Norm(taxicab norm or the Manhattan norm. | L2 Norm | Max Norm |
| :---: | :---: | :---: | :---: |
| Notation |  |
 | 
 |
|  | The L norm is calculated as the sum of the absolute vector values, where the absolute value of a scalar uses the notation $$\begin{vmatrix}
a
\end{vmatrix}$$.  | The L2 norm is calculated as the square root of the sum of the squared vector values. |  |
|  | $$\begin{Vmatrix}
\boldsymbol{v}
\end{Vmatrix} = 
\begin{vmatrix}
a_1
\end{vmatrix} + 
\begin{vmatrix}
a_2
\end{vmatrix} + 
\begin{vmatrix}
a_3
\end{vmatrix}$$ | 
 | 
 |
|  | In effect, the norm is a calculation of the Manhattan distance from the origin of the vector space. |  |  |
|  | The L1 norm is often used when fitting machine learning algorithms as a regularization method, e.g. a method to keep the coefficients of the model small, and in turn, the model less complex. | The L2 norm calculates the distance of the vector coordinate from the origin of the vector space. As such, it is also known as the Euclidean norm as it is calculated as the Euclidean distance from the origin. The result is a positive distance value. |  |
|  |  | Like the L1 norm, the L2 norm is often used when fitting machine learning algorithms as a regularization method, e.g. a method to keep the coefficients of the model small and, in turn, the model less complex.
By far, the L2 norm is more commonly used than other vector norms in machine learning. |  |



